from enum import Enum

class Command(Enum):
	LOGIN = 'LOGIN'
	ADD_IMAGE = 'ADD_IMAGE'
	UPDATE_IMAGE = 'UPDATE_IMAGE'
	DELETE_IMAGE='DELETE_IMAGE'
	CREATE_USER = 'CREATE_USER'
	SEARCH_BY_IMAGE = 'SEARCH_BY_IMAGE'
	BROWSE_BY_TAG = 'BROWSE_BY_TAG' 
	EXIT = 'EXIT'